apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: FileSystem
  accessMode: 
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate